export const styles = {
  container: { height: '100vh', backgroundColor: '#F5F5F5', fontFamily: 'sans-serif', display: 'flex', flexDirection: 'column' },
  profileContainer: { flex: 1, padding: 20, backgroundColor: '#fff', overflowY: 'auto' },
  profileHeader: { display: 'flex', flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  profileTitle: { fontSize: 28, fontWeight: 'bold', marginLeft: 10, color: '#333', margin: 0 },
  profileSubtitle: { fontSize: 16, color: '#666', marginBottom: 30 },
  profileSublabel: { fontSize: 14, color: '#666', marginBottom: 10 },
  inputGroup: { marginBottom: 25 },
  label: { display: 'block', fontSize: 18, fontWeight: '600', color: '#444', marginBottom: 10 },
  optionContainer: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  optionButton: { cursor: 'pointer', padding: '10px 15px', borderRadius: 20, backgroundColor: '#f0f0f0', border: '1px solid #ddd', color: '#333', fontWeight: '500' },
  optionButtonSelected: { cursor: 'pointer', padding: '10px 15px', borderRadius: 20, backgroundColor: '#3498db', border: '1px solid #3498db', color: '#fff', fontWeight: '500' },
  sliderValue: { textAlign: 'center', fontSize: 16, fontWeight: 'bold', color: '#3498db', marginBottom: 10 },
  saveButton: { cursor: 'pointer', width: '100%', backgroundColor: '#2ecc71', color: '#fff', fontSize: 18, fontWeight: 'bold', padding: 18, borderRadius: 12, textAlign: 'center', marginTop: 20, marginBottom: 40, border: 'none' },
  mainScreenContainer: { flex: 1, display: 'flex', flexDirection: 'column', height: '100%' },
  header: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: '15px 20px', borderBottom: '1px solid #eee', backgroundColor: '#fff', flexShrink: 0 },
  iconButton: { background: 'none', border: 'none', cursor: 'pointer', padding: 5 },
  appName: { fontSize: 22, fontWeight: 'bold', color: '#3498db', margin: 0 },
  deckContainer: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' },
  footer: { display: 'flex', flexDirection: 'row', justifyContent: 'space-evenly', padding: 20, backgroundColor: '#fff', flexShrink: 0 },
  actionButton: { cursor: 'pointer', width: 70, height: 70, borderRadius: 35, backgroundColor: '#fff', display: 'flex', justifyContent: 'center', alignItems: 'center', boxShadow: '0 1px 3px rgba(0,0,0,0.2)', border: 'none' },
  noMoreCards: { display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', padding: 20, textAlign: 'center' },
  noMoreCardsText: { fontSize: 20, fontWeight: 'bold', color: '#333', marginTop: 20, margin: 0 },
  noMoreCardsSubText: { fontSize: 16, color: '#666', marginTop: 10 },
  noMoreCardsButton: { cursor: 'pointer', backgroundColor: '#3498db', color: '#fff', fontSize: 16, fontWeight: 'bold', padding: '12px 25px', borderRadius: 25, marginTop: 20, border: 'none' },
  cardWrapper: { position: 'absolute', width: '90vw', height: '70vh', maxWidth: 400, maxHeight: 600, userSelect: 'none' },
  card: { position: 'relative', width: '100%', height: '100%', borderRadius: 20, backgroundColor: '#fff', overflow: 'hidden', boxShadow: '0 2px 10px rgba(0,0,0,0.2)', cursor: 'pointer' },
  cardImage: { width: '100%', height: '100%', objectFit: 'cover' },
  gradientOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '50%', background: 'linear-gradient(to top, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0) 100%)' },
  cardInfo: { position: 'absolute', bottom: 20, left: 20, right: 20 },
  cardName: { fontSize: 32, fontWeight: 'bold', color: '#fff', textShadow: '1px 1px 3px rgba(0,0,0,0.7)', margin: 0 },
  cardCuisine: { fontSize: 20, color: '#eee', textShadow: '1px 1px 3px rgba(0,0,0,0.7)', margin: 0 },
  detailsView: { position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.85)', padding: 20, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', color: '#fff' },
  detailsTitle: { fontSize: 20, fontWeight: 'bold', marginTop: 20, marginBottom: 10, borderBottom: '1px solid #555', paddingBottom: 5 },
  detailsSummary: { fontSize: 16, color: '#ddd', lineHeight: 1.5 },
  highlightItem: { display: 'flex', flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  highlightText: { color: '#ddd', fontSize: 16, marginLeft: 10 },
  infoRow: { display: 'flex', justifyContent: 'space-around', marginTop: 20, paddingTop: 15, borderTop: '1px solid #555' },
  infoPill: { display: 'flex', flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)', padding: '8px 12px', borderRadius: 20 },
  infoPillText: { color: '#fff', marginLeft: 5, fontWeight: '600' },
  savedContainer: { display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: '#fff' },
  savedHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: 15, borderBottom: '1px solid #eee' },
  savedTitle: { fontSize: 20, fontWeight: 'bold', margin: 0 },
  noSavedItems: { flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' },
  noSavedText: { fontSize: 18, fontWeight: '600', color: '#555', marginTop: 20, margin: 0 },
  noSavedSubText: { fontSize: 14, color: '#888', marginTop: 5 },
  savedItem: { display: 'flex', padding: 15, alignItems: 'center', borderBottom: '1px solid #f0f0f0' },
  savedItemImage: { width: 80, height: 80, borderRadius: 12, objectFit: 'cover' },
  savedItemInfo: { flex: 1, marginLeft: 15 },
  savedItemName: { fontSize: 18, fontWeight: 'bold', margin: 0 },
  savedItemCuisine: { fontSize: 14, color: '#666', margin: '4px 0 0 0' },
  savedItemDetailsText: { fontSize: 14, color: '#666', marginLeft: 4 },
  navigateButton: { cursor: 'pointer', backgroundColor: '#2ecc71', width: 50, height: 50, borderRadius: 25, display: 'flex', justifyContent: 'center', alignItems: 'center', border: 'none' },
  sliderContainer: { paddingTop: 20, paddingBottom: 10, maxWidth: '500px', margin: '0 auto' },
  sliderTrack: { position: 'relative', height: 4, backgroundColor: '#ddd', borderRadius: 2 },
  sliderRange: { position: 'absolute', height: 4, backgroundColor: '#3498db', borderRadius: 2 },
  sliderHandle: { position: 'absolute', top: '50%', width: 24, height: 24, backgroundColor: '#fff', border: '2px solid #3498db', borderRadius: '50%', transform: 'translate(-50%, -50%)', cursor: 'pointer', boxShadow: '0 1px 3px rgba(0,0,0,0.2)', zIndex: 1 },
  sliderLabels: { position: 'relative', height: 20, marginTop: 15 },
  sliderLabel: { fontSize: 14, color: '#666', position: 'absolute', transform: 'translateX(-50%)' },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',          
    width: '100%',           
    padding: 40,
    textAlign: 'center',
    minHeight: '60vh',     
  },

  loadingText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    margin: '20px 0 10px 0', 
  },

  loadingSubText: {
    fontSize: 16,
    color: '#666',
    margin: 0
  },

};